name = "nouns-agora"
compatibility_date = "2022-09-04"
main = "dist/worker.js"
account_id = "86fdf8ef811b4d0aa8954fa036684ea3"
logpush = true

[env.dev]
vars = { ENVIRONMENT = "dev", DEPLOYMENT = "nouns", HONEYCOMB_DATASET = "nouns-agora-dev" }
kv_namespaces = [
    { binding = "STATEMENTS", id = "f1794afcd31a4dd0884c310251251f00", preview_id = "a0f4891449204b0fbdf564d0d1f339dd" },
    { binding = "EMAILS", id = "4f97982037324363a82d515a65605d40", preview_id = "bb754b77fdac44b4a17521045bd056ad" },
    { binding = "APPLICATION_CACHE", id = "06a6407a4bc24a18bf7989383147a21f", preview_id = "75500b3f99ae4b15b633d6ce3eddd87c" },
    { binding = "INDEXER", id = "355e22c9ae734ff999094adc275f6829", preview_id = "59da2e88635249b7b941cb5379c3553a" },
    { binding = "LAST_BLOCKED_FETCHED", id = "9ad843c85209463083cc998fd24b4e40", preview_id = "44e6dad6150145a3bee032d2822a5fca" }
]

[env.staging]
name = "nouns-agora-staging"
vars = { ENVIRONMENT = "staging", DEPLOYMENT = "nouns", HONEYCOMB_DATASET = "nouns-agora-staging" }
kv_namespaces = [
    { binding = "STATEMENTS", id = "dc57f476cdbd4728962dd2b6bf679f32" },
    { binding = "EMAILS", id = "bb85e58040c74a11af5eb80a29eaf30c" },
    { binding = "APPLICATION_CACHE", id = "b7d98e25d35841a1b326f2962eb1d77f" },
    { binding = "INDEXER", id = "61de0b59617f4700a9a07c6f9149cbd3" },
    { binding = "LAST_BLOCKED_FETCHED", id = "7ddc81893e92485083c2fd052c47c5ef" }
]

[env.prod]
name = "nouns-agora"
vars = { ENVIRONMENT = "prod", DEPLOYMENT = "nouns", HONEYCOMB_DATASET = "nouns-agora-prod" }
account_id = "d0222542a05849995856d260759717d4"
kv_namespaces = [
    { binding = "STATEMENTS", id = "dd8a0cf1ad9c4e6b911a4e3da3cd334f" },
    { binding = "EMAILS", id = "29d54efee06a44f9adb0dbb9e93e840f" },
    { binding = "APPLICATION_CACHE", id = "0bca6afc17d341e383860ba7ff730868" },
    { binding = "INDEXER", id = "872aec279fb24309bf14761cc0ae58c1" },
    { binding = "LAST_BLOCKED_FETCHED", id = "3614f4c794f64aa488a12523d7980c1d" }
]

[build]
command = "yarn build-worker"

[site]
bucket = "../frontend/build"

[triggers]
crons = ["0 * * * *", "5,10,15,20,25,30,35,40,45,50,55 * * * *"]
