compatibility_date = "2022-11-30"
main = "dist/worker.js"
logpush = true

[env.dev]
name = "nouns-agora-dev"
account_id = "86fdf8ef811b4d0aa8954fa036684ea3"
kv_namespaces = [
    { binding = "EMAILS", id = "4f97982037324363a82d515a65605d40", preview_id = "bb754b77fdac44b4a17521045bd056ad" }
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.dev.vars]
ENVIRONMENT = "dev"
DEPLOYMENT = "nouns"
HONEYCOMB_DATASET = "nouns-agora-dev"
ADMIN_API_KEY = ''
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable'
BLOCK_STEP_SIZE = "100"
ALLOW_READS_PERCENTAGE = "100"
USE_CACHE_PERCENTAGE = "100"

[env.staging]
name = "nouns-agora-staging"
account_id = "86fdf8ef811b4d0aa8954fa036684ea3"

kv_namespaces = [
    { binding = "EMAILS", id = "bb85e58040c74a11af5eb80a29eaf30c" }
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
DEPLOYMENT = "nouns"
HONEYCOMB_DATASET = "nouns-agora-dev"
ADMIN_API_KEY = ''
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable'
BLOCK_STEP_SIZE = "100"
ALLOW_READS_PERCENTAGE = "100"
USE_CACHE_PERCENTAGE = "100"

[env.prod]
name = "nouns-agora-prod"
account_id = "d0222542a05849995856d260759717d4"
kv_namespaces = [
    { binding = "EMAILS", id = "29d54efee06a44f9adb0dbb9e93e840f" },
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.prod.vars]
ENVIRONMENT = "prod"
DEPLOYMENT = "nouns"
HONEYCOMB_DATASET = "nouns-agora-prod"
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable1'
BLOCK_STEP_SIZE = "100"
ALLOW_READS_PERCENTAGE = "100"
USE_CACHE_PERCENTAGE = "100"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDurableObjectV1"]

[build]
command = "yarn build-worker"

[site]
bucket = "../frontend/build"
