compatibility_date = "2022-11-30"
main = "dist/worker.js"
logpush = true
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
name = "nouns-agora-dev"
account_id = "f843baa950d11ddb130ad0f649fc1fa2"
kv_namespaces = [
    { binding = "EMAILS", id = "2e5addad8c4a4527bab2b98267b27851" }
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.dev.vars]
ENVIRONMENT = "dev"
DEPLOYMENT = "nouns"
ADMIN_API_KEY = ''
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'sepolia'
ALLOW_READS_PERCENTAGE = "100"
USE_CACHE_PERCENTAGE = "100"

[env.prod]
name = "nouns-agora-prod"
account_id = "d0222542a05849995856d260759717d4"
kv_namespaces = [
    { binding = "EMAILS", id = "29d54efee06a44f9adb0dbb9e93e840f" },
]
durable_objects.bindings = [
    { name = "STORAGE_OBJECT", class_name = "StorageDurableObjectV1" }
]
analytics_engine_datasets = [
    { binding = "STORAGE_ANALYTICS" }
]

[env.prod.vars]
ENVIRONMENT = "prod"
DEPLOYMENT = "nouns"
PRIMARY_DURABLE_OBJECT_INSTANCE_NAME = 'stable8'
ALLOW_READS_PERCENTAGE = "100"
USE_CACHE_PERCENTAGE = "100"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StorageDurableObjectV1"]

[build]
command = "yarn build-worker"

[site]
bucket = "../frontend/dist"
